name: Test Fabric

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]
    types: [opened, reopened, ready_for_review, synchronize]  # added `ready_for_review` since draft is skipped
    paths:
      - ".actions/**"
      - "requirements/fabric/**"
      - "src/lightning/fabric/**"
      - "src/lightning_fabric/*"
      - "tests/tests_fabric/**"
      - "pyproject.toml"  # includes pytest config
      - ".github/workflows/ci-tests-fabric.yml"
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

env:
  FREEZE_REQUIREMENTS: 1

defaults:
  run:
    shell: bash

jobs:
  fabric-cpu:
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: "macOS-11", pkg-name: "lightning", python-version: "3.8", pytorch-version: "1.11"}
          - {os: "macOS-11", pkg-name: "lightning", python-version: "3.9", pytorch-version: "1.12"}
          - {os: "ubuntu-20.04", pkg-name: "lightning", python-version: "3.9", pytorch-version: "1.11"}
          - {os: "ubuntu-20.04", pkg-name: "lightning", python-version: "3.10", pytorch-version: "1.12"}
          - {os: "windows-2022", pkg-name: "lightning", python-version: "3.9", pytorch-version: "1.11"}
          - {os: "windows-2022", pkg-name: "lightning", python-version: "3.10", pytorch-version: "1.12"}
          # only run PyTorch latest with Python latest
          - {os: "macOS-11", pkg-name: "lightning", python-version: "3.10", pytorch-version: "1.13"}
          - {os: "ubuntu-20.04", pkg-name: "lightning", python-version: "3.10", pytorch-version: "1.13"}
          - {os: "windows-2022", pkg-name: "lightning", python-version: "3.10", pytorch-version: "1.13"}
          # "oldest" versions tests, only on minimum Python
          - {os: "macOS-11", pkg-name: "lightning", python-version: "3.8", pytorch-version: "1.11", requires: "oldest"}
          - {os: "ubuntu-20.04", pkg-name: "lightning", python-version: "3.8", pytorch-version: "1.11", requires: "oldest"}
          - {os: "windows-2022", pkg-name: "lightning", python-version: "3.8", pytorch-version: "1.11", requires: "oldest"}
          # "fabric" installs the standalone package
          - {os: "macOS-11", pkg-name: "fabric", python-version: "3.8", pytorch-version: "1.13"}
          - {os: "ubuntu-20.04", pkg-name: "fabric", python-version: "3.8", pytorch-version: "1.13"}
          - {os: "windows-2022", pkg-name: "fabric", python-version: "3.8", pytorch-version: "1.13"}
    timeout-minutes: 25  # because of building grpcio on Mac
    env:
      PACKAGE_NAME: ${{ matrix.pkg-name }}
      FREEZE_REQUIREMENTS: 1
      PYPI_CACHE: "_pip-wheels"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: basic setup
      run: pip install -q -r .actions/requirements.txt

    - name: Set min. dependencies
      if: ${{ matrix.requires == 'oldest' }}
      run: python .actions/assistant.py replace_oldest_ver

    - name: Adjust PyTorch versions in requirements files
      if: ${{ matrix.requires != 'oldest' }}
      run: |
        for fpath in `ls requirements/**/*.txt`; do \
          python ./requirements/pytorch/adjust-versions.py $fpath ${{ matrix.pytorch-version }}; \
        done
        cat requirements/fabric/base.txt

    - name: pip wheels cache
      uses: actions/cache/restore@v3
      with:
        path: ${{ env.PYPI_CACHE }}
        key: pypi_wheels
    - run: |
        mkdir -p $PYPI_CACHE
        ls -lh $PYPI_CACHE

    - name: Switch PyTorch URL
      run: python -c "print('TORCH_URL=https://download.pytorch.org/whl/' + str('test/cpu/torch_test.html' if '${{matrix.release}}' == 'pre' else 'cpu/torch_stable.html'))" >> $GITHUB_ENV

    - name: Install package & dependencies
      run: |
        pip install -e .[test] "pytest-timeout" -U -f ${TORCH_URL} -f ${PYPI_CACHE} --prefer-binary
        pip install -r requirements/fabric/strategies.txt -f ${PYPI_CACHE} --prefer-binary
        pip list
    - name: Dump handy wheels
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      continue-on-error: true
      uses: ./.github/actions/pip-wheels
      with:
        wheel-dir: ${{ env.PYPI_CACHE }}
        torch-url: ${{ env.TORCH_URL }}
        cache-key: "pypi_wheels"

    - name: Adjust tests
      if: ${{ matrix.pkg-name != 'lightning' }}
      run: |
        python .actions/assistant.py copy_replace_imports --source_dir="./tests" \
          --source_import="lightning.fabric" --target_import="lightning_fabric"

    - name: Testing Warnings
      working-directory: tests/tests_fabric
      # needs to run outside of `pytest`
      run: python utilities/test_warnings.py

    - name: Switch coverage scope
      run: python -c "print('COVERAGE_SCOPE=' + str('lightning' if '${{matrix.pkg-name}}' == 'lightning' else 'lightning_fabric'))" >> $GITHUB_ENV

    - name: Testing Fabric
      working-directory: tests/tests_fabric
      # NOTE: do not include coverage report here, see: https://github.com/nedbat/coveragepy/issues/1003
      run: |
        python -m coverage run --source ${{ env.COVERAGE_SCOPE }} \
          -m pytest -v --timeout=30 --durations=50

    - name: Statistics
      if: success()
      working-directory: tests/tests_fabric
      run: |
        coverage report
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      # see: https://github.com/actions/toolkit/issues/399
      continue-on-error: true
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: tests/tests_fabric/coverage.xml
        flags: ${{ env.COVERAGE_SCOPE }},cpu,pytest,python${{ matrix.python-version }}
        name: CPU-coverage
        fail_ci_if_error: false
